const PREV_CIRCLES = 'PREV_CIRCLES';
const SEND_CIRCLE = 'SEND_CIRCLE';
const NEW_CIRCLE = 'NEW_CIRCLE';

const PREV_SQUARES = 'PREV_SQUARES';
const SEND_SQUARE = 'SEND_SQUARE';
const NEW_SQUARE = 'NEW_SQUARE';

module.exports = {
  PREV_CIRCLES,
  SEND_CIRCLE,
  NEW_CIRCLE,
  PREV_SQUARES,
  SEND_SQUARE,
  NEW_SQUARE,
}